name: Deploy backend testnet env

on:
  push:
    branches: ['main']

env:
  REMOTE_HOST: deploy@167.99.30.150
  # DOCKER_COMPOSE_FILE: docker-compose.deploy.yml
  STACK: nest-boilerplate-testnet
  # DOCKER_REGISTRY: registry.digitalocean.com
  APP_BACKEND_HOST: api.1811labs.com
  DOCKER_BUILDKIT: 1
  # COMPOSE_PROFILES: infra
  IMAGE_NAME: 1811labs/nest-boilerplate

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TESTNET_SSH_KEY }}
          known_hosts: ${{ secrets.TESTNET_KNOWN_HOSTS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - run: echo "IMAGE_TAG=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Build and push web image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          file: Dockerfile
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Login to Docker registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.DOCKER_REGISTRY }}
      #     username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      #     password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Deploy backend
        run: |
          task deploy:init
          task deploy:push
          task docker:deploy
